<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nomor telepon diawali 62, 7-13 karakt_13c933</name>
   <tag></tag>
   <elementGuidId>1b8f3c3f-aa21-42ff-b099-9832807c2cb9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='usernamesignup']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#usernamesignup</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0a270843-5b52-4267-892a-17adabf5ad12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c7826c5b-3c96-486f-978c-20d1dd2cb3af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>usernamesignup</value>
      <webElementGuid>a3fcf142-4ba8-4e9c-9cdf-492e77ba3853</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>usernamesignup</value>
      <webElementGuid>b6c4a734-fc4b-4508-a290-41fd707d6f5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>usernamesignup</value>
      <webElementGuid>d5b9e905-530f-4127-843a-72ca2dbbe940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full h-12 block leading-5 relative py-2 px-4 rounded bg-white dark:bg-gray-800 border focus:border-2 border-gray-500 overflow-x-auto focus:outline-none focus:border-primary-600 focus:ring-0 dark:text-gray-200 dark:border-gray-400 dark:focus:border-primary-200 peer</value>
      <webElementGuid>575e7916-cae6-4480-ab7f-aafdb8e15ccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;usernamesignup&quot;)</value>
      <webElementGuid>3c946e4b-dfdf-40ee-b0e4-a722f192b4ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='usernamesignup']</value>
      <webElementGuid>05d3960b-1029-4a80-a70e-d53db231b8b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cardContainer']/div/div/div/div[2]/div[3]/input</value>
      <webElementGuid>d6d86521-5148-4062-b643-e29f073c4bec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>0995b83e-cdf7-4b83-ae91-a077334e5826</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'usernamesignup' and @id = 'usernamesignup']</value>
      <webElementGuid>edb3d982-7e93-439e-9f64-83d431fff4d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
