<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Login here_emailsignup</name>
   <tag></tag>
   <elementGuidId>bd2df816-313d-492e-9dd9-bf127f4577d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='emailsignup']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#emailsignup</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cbe93ddb-a187-4d8e-b11e-3af9307076e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>e3ae4ef7-b9e5-4baf-9fd8-c7fdada54655</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>emailsignup</value>
      <webElementGuid>17ebbed7-f19f-4a83-bb30-acc80a9c9749</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>emailsignup</value>
      <webElementGuid>a4ab1007-f1d7-45ac-aa85-e039e6df9131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>emailsignup</value>
      <webElementGuid>26db404e-f64e-4576-b3ba-857a7fa3c494</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full h-12 block leading-5 relative py-2 px-4 rounded bg-white dark:bg-gray-800 border focus:border-2 border-gray-500 overflow-x-auto focus:outline-none focus:border-primary-600 focus:ring-0 dark:text-gray-200 dark:border-gray-400 dark:focus:border-primary-200 peer</value>
      <webElementGuid>44773e52-f33f-4ea1-a383-3d7a93670777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;emailsignup&quot;)</value>
      <webElementGuid>9358335d-03d6-4b06-8639-a85e750864cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='emailsignup']</value>
      <webElementGuid>7df0f066-1e9e-4f8a-a28a-1f7249a98eb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cardContainer']/div/div/div/div[2]/div/input</value>
      <webElementGuid>aad2b9cf-d346-46c8-9ee1-f6cb295afb66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>04ad4b84-bcbb-4172-ab10-9be991aa9164</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'emailsignup' and @id = 'emailsignup']</value>
      <webElementGuid>4a9b1514-559d-48b9-91ab-131811ae9999</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
