<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Hotel Gassinn Leaflet   OpenStreetMap c_fcf839</name>
   <tag></tag>
   <elementGuidId>3d3f7a5a-39cf-40e2-bf8c-333da5118283</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#map</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='map']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Hotel Gassinn×+− Leaflet | © OpenStreetMap contributors&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ac6f9c95-b35b-4c05-abc5-fd1bc5c4dcd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>map</value>
      <webElementGuid>fac135df-9360-49b1-8143-35b68d470526</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>leaflet-container leaflet-touch leaflet-retina leaflet-fade-anim leaflet-grab leaflet-touch-drag leaflet-touch-zoom</value>
      <webElementGuid>ff79585e-a792-41a5-aac1-0163400837af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2657a5c5-b370-4817-9fa4-8758f90cfefa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hotel Gassinn×+− Leaflet | © OpenStreetMap contributors</value>
      <webElementGuid>b0cc4651-cf65-4ebf-9601-fae35f66fe0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;map&quot;)</value>
      <webElementGuid>7b36ec31-33b1-4b65-a9d8-1ed5d770710c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='map']</value>
      <webElementGuid>f1bde717-39fb-491e-98eb-0ab5bf6404ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/section[2]/div/div/div/div/div/div</value>
      <webElementGuid>ed9c7637-c369-42f5-be75-8f4273044f2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome to HoTa'])[1]/following::div[7]</value>
      <webElementGuid>f9de05a8-2fb1-42cb-97f3-04289ceaaf64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Register'])[1]/following::div[10]</value>
      <webElementGuid>0bade63e-698d-41bd-925e-80e1b5cb8695</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div</value>
      <webElementGuid>140c548d-7717-426f-9840-0bd64e5cd6a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'map' and (text() = 'Hotel Gassinn×+− Leaflet | © OpenStreetMap contributors' or . = 'Hotel Gassinn×+− Leaflet | © OpenStreetMap contributors')]</value>
      <webElementGuid>caa1a69a-4edb-4afa-b007-d0e87d9ac440</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
